"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['srtfixer.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'iconfile': '/Users/hectortoledo/Projects/SRTFixer/icon.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
